# Use an official Golang image matching your required version
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum /app/
RUN go mod download

COPY . /app/

RUN CGO_ENABLED=0 GOOS=linux go build -o /exe /app/.

FROM alpine:latest

COPY --from=builder /exe /exe
COPY env.json /
EXPOSE 5050

CMD ["/exe"]